# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31c50270abc278b610146e56e0289542d46d41542bdf3d283fd76f5cb917981ff2c27451e8604b3743ca6af5d1ceb041ae7835ffa5895c881731c34d88f03167

test:
  secret_key_base: 35d2ab7e13a5f1ab469a3cffe6c42e2a7a2502b11ce66c9609a6049e2c207de264d393a2864154e45ac89f4c42387d78300bb639c6777f6cb1c93d664d104239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
